M48
; DRILL file {KiCad 9.0.1} date 2025-05-08T00:01:41-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-08T00:01:41-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X91.44Y-44.45
X91.44Y-46.99
X91.44Y-49.53
T2
X34.925Y-24.13
X34.925Y-69.85
X64.77Y-46.99
M30
