M48
; DRILL file {KiCad 9.0.1} date 2025-05-07T23:59:27-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-07T23:59:27-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X40.64Y-32.385
X40.64Y-74.295
X73.025Y-32.385
X73.025Y-74.295
M30
